//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 06.11.2015 15:22:00 by NFX.Templatization.TextCSTemplateCompiler at PC

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 
using NFX.Wave.Templatization; 
using NFX.Wave; 
using NFX; 

namespace TinyUrlSite.Pages 
{

 ///<summary>
 /// Error page
 ///</summary>
 public  class Error : TinyUrlSite.Pages.Master
 {


public string Message { get; set; }


     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( Error._0_S_LITERAL_0 );

     }
    protected override void  renderBody()
    {
        Target.Write( Error._0_S_LITERAL_1 );
        Target.Write(Target.Encode( Message ));
        Target.Write( Error._0_S_LITERAL_2 );
        Target.Write(Target.Encode( RenderingContext ));
        Target.Write( Error._0_S_LITERAL_3 );

    }


     #region Literal blocks content
        private const string _0_S_LITERAL_0 = @"

"; 
        private const string _0_S_LITERAL_1 = @"

<style>
    #divRoot {
       width: 100%; 
       height: 50px; 
       margin-top: 100px;
       text-align: center;
   }
</style>

<h1>An error has occured</h1>
<div id=""divRoot"">
    "; 
        private const string _0_S_LITERAL_2 = @" aaaa "; 
        private const string _0_S_LITERAL_3 = @"
</div>"; 
     #endregion

 }//class
}//namespace
