//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 05.11.2015 0:18:43 by NFX.Templatization.TextCSTemplateCompiler at PC

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 
using NFX.Wave.Templatization; 
using NFX.Wave; 
using NFX; 

namespace TinyUrlSite.Pages 
{

 ///<summary>
 /// Master page for all pages on this site
 ///</summary>
 public abstract class Master : NFX.Wave.Templatization.WaveTemplate
 {


    public virtual string Title { get { return "Shorten URLs"; } }
    protected abstract void renderBody();


     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( Master._76_S_LITERAL_0 );
        Target.Write( Master._76_S_LITERAL_1 );
        Target.Write(Target.Encode( Title ));
        Target.Write( Master._76_S_LITERAL_2 );
      renderBody();
        Target.Write( Master._76_S_LITERAL_3 );

     }


     #region Literal blocks content
        private const string _76_S_LITERAL_0 = @"
"; 
        private const string _76_S_LITERAL_1 = @"
<!DOCTYPE html>
<html>
<head>
    <title>"; 
        private const string _76_S_LITERAL_2 = @"</title>
    <meta http-equiv=""Content-Type"" content=""text/html; charset=utf-8"" />
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0, user-scalable=no"">
</head>
<body>
    "; 
        private const string _76_S_LITERAL_3 = @"
</body>
</html>"; 
     #endregion

 }//class
}//namespace
